{% set name = "sqlalchemy-omnisci" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0b1ced50ef47f2b218bf743c65c664398f4bb7c3e0a76607451fbd3c8cbf2cca

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - setuptools-scm
    - wheel
  run:
    - python >=3.6
    - sqlalchemy 1.*
    - pyomniscidb >=5.5.2
    - pyomnisci >=0.27.0

test:
  imports:
    - sqlalchemy_omnisci

about:
  home: https://github.com/omnisci/sqlalchemy-omnisci
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: OmniSci SQLAlchemy Driver
  description: |
    OmniSci SQLAlchemy Driver
  doc_url: https://omnisci.github.io/sqlalchemy-omnisci
  dev_url: https://github.com/omnisci/sqlalchemy-omnisci

extra:
  recipe-maintainers:
    - xmnlab
